In [27]:
import numpy as np
import torch
from torch import nn

net1 = nn.Sequential(
    nn.Linear(30,40),
    nn.ReLU(),
    nn.Linear(40,50),
    nn.ReLU(),
    nn.Linear(50,10)
)

In [28]:
w1 = net1[0].weight
b1 = net1[0].bias

In [29]:
print(w1)

Parameter containing:
tensor([[-0.0054, -0.0990,  0.0798,  ..., -0.1337, -0.1228, -0.0401],
        [-0.1110,  0.0334,  0.0341,  ..., -0.0965,  0.1035,  0.1584],
        [ 0.0650,  0.0273, -0.0967,  ..., -0.1705,  0.1735, -0.1291],
        ...,
        [ 0.0694,  0.1602, -0.0494,  ..., -0.1659, -0.0925,  0.1007],
        [-0.0875,  0.0370, -0.0351,  ..., -0.0916, -0.1541, -0.0265],
        [-0.0935,  0.1190,  0.0916,  ...,  0.1156,  0.0921,  0.0403]],
       requires_grad=True)


In [30]:
net1[0].weight.data = torch.from_numpy(np.random.uniform(2,5,size=(40,30)))

In [31]:
print(net1[0].weight)

Parameter containing:
tensor([[2.4927, 2.4294, 4.1439,  ..., 2.2738, 2.8246, 4.0324],
        [2.3002, 3.0353, 2.2383,  ..., 4.6224, 2.2438, 2.8907],
        [4.6871, 2.2054, 3.5648,  ..., 2.1451, 3.5613, 2.0716],
        ...,
        [4.0252, 3.8234, 2.3096,  ..., 2.7168, 4.2191, 4.3770],
        [4.6017, 4.3739, 2.6870,  ..., 2.3041, 2.2583, 3.0866],
        [4.8226, 3.5464, 2.1238,  ..., 3.3191, 4.0188, 2.0128]],
       dtype=torch.float64, requires_grad=True)


In [32]:
for layer in net1:
    if isinstance(layer, nn.Linear):
        param_shape = layer.weight.shape
        layer.weight.data = torch.from_numpy(np.random.normal(0, 0.5, size=param_shape)) 

In [35]:
class  sim_net(nn.Module):
    def __init__(self):
        super(sim_net, self).__init__()
        self.l1 = nn.Sequential(
            nn.Linear(30, 40),
            nn.ReLU()
        )
        self.l1[0].weight.data = torch.randn(40, 30) 
        
        self.l2 = nn.Sequential(
            nn.Linear(40, 50),
            nn.ReLU()
        )
        
        self.l3 = nn.Sequential(
            nn.Linear(50, 10),
            nn.ReLU()
        )
    
    def forward(self, x):
        x = self.l1(x)
        x =self.l2(x)
        x = self.l3(x)
        return x

In [36]:
net2 = sim_net()

In [37]:
for i in net2.children():
    print(i)

Sequential(
  (0): Linear(in_features=30, out_features=40, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Linear(in_features=40, out_features=50, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Linear(in_features=50, out_features=10, bias=True)
  (1): ReLU()
)


In [38]:
for i in net2.modules():
    print(i)

sim_net(
  (l1): Sequential(
    (0): Linear(in_features=30, out_features=40, bias=True)
    (1): ReLU()
  )
  (l2): Sequential(
    (0): Linear(in_features=40, out_features=50, bias=True)
    (1): ReLU()
  )
  (l3): Sequential(
    (0): Linear(in_features=50, out_features=10, bias=True)
    (1): ReLU()
  )
)
Sequential(
  (0): Linear(in_features=30, out_features=40, bias=True)
  (1): ReLU()
)
Linear(in_features=30, out_features=40, bias=True)
ReLU()
Sequential(
  (0): Linear(in_features=40, out_features=50, bias=True)
  (1): ReLU()
)
Linear(in_features=40, out_features=50, bias=True)
ReLU()
Sequential(
  (0): Linear(in_features=50, out_features=10, bias=True)
  (1): ReLU()
)
Linear(in_features=50, out_features=10, bias=True)
ReLU()


In [39]:
for layer in net2.modules():
    if isinstance(layer, nn.Linear):
        param_shape = layer.weight.shape
        layer.weight.data = torch.from_numpy(np.random.normal(0, 0.5, size=param_shape))


In [40]:
from torch.nn import init
print(net1[0].weight)

Parameter containing:
tensor([[ 1.3137,  0.3886,  0.0936,  ...,  0.1792,  0.0219, -0.1169],
        [-0.4296, -0.0291,  0.7261,  ..., -0.2640, -0.5652, -0.1115],
        [ 0.0204,  0.0466,  0.3861,  ..., -0.6062,  0.2590,  0.3339],
        ...,
        [-0.9081, -0.1344,  0.1048,  ..., -0.3535, -0.4712,  0.7374],
        [ 0.0226,  0.8933,  0.5453,  ..., -0.4622, -0.0902, -0.8340],
        [ 0.3551, -0.0007, -0.0105,  ..., -1.1080, -0.0909, -0.4083]],
       dtype=torch.float64, requires_grad=True)


In [41]:
init.xavier_uniform(net1[0].weight)

/home/xiuchao/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  """Entry point for launching an IPython kernel.


Parameter containing:
tensor([[-0.0673,  0.0515,  0.2239,  ..., -0.2561, -0.2130, -0.2082],
        [-0.0255, -0.0344,  0.1222,  ...,  0.2127,  0.0450,  0.1603],
        [ 0.0412, -0.1725,  0.0656,  ...,  0.2216,  0.2589,  0.0074],
        ...,
        [ 0.1048, -0.1308,  0.0005,  ..., -0.0086,  0.2763, -0.2246],
        [ 0.0200,  0.1959, -0.2546,  ...,  0.2891,  0.2497,  0.2694],
        [-0.2143, -0.1083, -0.0347,  ..., -0.1009,  0.0443,  0.2769]],
       dtype=torch.float64, requires_grad=True)

In [42]:
print(net1[0].weight)

Parameter containing:
tensor([[-0.0673,  0.0515,  0.2239,  ..., -0.2561, -0.2130, -0.2082],
        [-0.0255, -0.0344,  0.1222,  ...,  0.2127,  0.0450,  0.1603],
        [ 0.0412, -0.1725,  0.0656,  ...,  0.2216,  0.2589,  0.0074],
        ...,
        [ 0.1048, -0.1308,  0.0005,  ..., -0.0086,  0.2763, -0.2246],
        [ 0.0200,  0.1959, -0.2546,  ...,  0.2891,  0.2497,  0.2694],
        [-0.2143, -0.1083, -0.0347,  ..., -0.1009,  0.0443,  0.2769]],
       dtype=torch.float64, requires_grad=True)
